version: "3"

services:

  edgedb:
    image: edgedb/edgedb
    container_name: edgedb
    environment:
      # EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_TLS_CERT_MODE: generate_self_signed
      EDGEDB_SERVER_USER: edgedb
      EDGEDB_SERVER_PASSWORD: edgedb
    volumes:
      - "./dbschema:/dbschema"
      - "./data:/var/lib/edgedb/data"
    ports:
      - "5656:5656"
